# Generated by Django 4.2.7 on 2023-12-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
